In [1]:
import numpy as np
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])
C = A + B
print("--------------------------")
print("Matrix A ")
print(A)
print("--------------------------")
print("Matrix B")
print(B)
print("--------------------------")
print("Addition of matrix A and B")
print(C)
print("--------------------------")

--------------------------
Matrix A 
[[1 2]
 [3 4]]
--------------------------
Matrix B
[[5 6]
 [7 8]]
--------------------------
Addition of matrix A and B
[[ 6  8]
 [10 12]]
--------------------------
